In [1]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Yes, there is a difference in the data type of variables list_ and array_list.

The list_ variable is of type list while the array_list variable is of type numpy.ndarray.

In [3]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

import numpy as np

# Define list and numpy array
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in the list
for element in list_:
    print(type(element))

# Print data type of each element in the numpy array
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
# Q3

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

array_list = np.array(object = list_, dtype = int)

# Data types of elements in list_
for i in list_:
    print(type(i))

# Data types of elements in array_list
for i in array_list:
    print(type(i))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [10]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print(num_array.shape)  # (2, 3)
print(num_array.size)   # 6


(2, 3)
6


In [11]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

arr_zeros = np.zeros((3,3))
print(arr_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?

ide=np.eye((5,5))
ide

TypeError: 'tuple' object cannot be interpreted as an integer